# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b4950db00b716736c78c2393505c3b78b9d00b6f5f2277bd6f576e60c743aac04e6e2c8cf7c9af25786765128d810cf2a14802e512edeaa271e0c7f581f2065
  resource_download_strategy: xml_urls
  resource_xml_urls:  [
                        'http://dev.hexagonalwax.com.s3-website-eu-west-1.amazonaws.com/engineering-test/resources/supplier/WNP-SWCL001-010.xml',
                        'http://dev.hexagonalwax.com.s3-website-eu-west-1.amazonaws.com/engineering-test/resources/supplier/ZDW-EOWW005-010.xml'
                      ]

test:
  secret_key_base: 8e33e739d872513ce442da3c023e5fb9ccd5937ab241f73dbd308c67bb328c0a191fc4ec7df4e3e2605b1a09935a4b6cad461bcba222d0c1c7500dd22dafc693,
  resource_download_strategy: xml_urls
  resource_xml_urls:  [
                        'http://dev.hexagonalwax.com.s3-website-eu-west-1.amazonaws.com/engineering-test/resources/supplier/WNP-SWCL001-010.xml',
                        'http://dev.hexagonalwax.com.s3-website-eu-west-1.amazonaws.com/engineering-test/resources/supplier/ZDW-EOWW005-010.xml'
                      ]

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  resource_download_strategy: <%= ENV["RESOURCE_DOWNLOAD_STRATEGY"] %>
  resource_xml_urls:  <%= ENV["RESOURCE_URLS"] %>
